### Test GET request
GET http://localhost:8080/?name=test
Accept: application/json

### Test POST request
POST http://localhost:8080
Content-Type: application/json

{
    "name": "arul",
    "email": "arul@mail.com"
}

